Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и
единицами.

In [55]:
import numpy as np
arr = np.arange(64).reshape(8,8)
for i in range (0, 8):
  for j in range(8):
    arr[i][j] = i % 2 != j % 2
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания
необходимо использовать функцию arrange.

In [56]:
arr = np.arange(25).reshape(5,5)
for i in range (0, 5):
  arr[i] = arr[0]
print(arr)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


Создать массив 3x3x3 со случайными значениями.

In [57]:
import numpy as np
from random import randint

arr = np.arange(27).reshape(3, 3, 3)
for i in range (0, 3):
  for j in range (0, 3):
    for k in range(0, 3):
      arr[i][j][k] = randint(0, 1000)
print(arr)

[[[540 850 204]
  [344 822 395]
  [564 482 628]]

 [[911 313 139]
  [113 888 491]
  [962   3 565]]

 [[ 44 860 921]
  [271 487 577]
  [201 405 668]]]


Создать матрицу с 0 внутри, и 1 на границах.

In [58]:
import numpy as np
from random import randint

arr = np.arange(36).reshape(6, 6)
for i in range (0, 6):
  for j in range (0, 6):
    if i == 0 or i == len(arr) - 1 or j == 0 or j == len(arr) - 1:
      arr[i][j] = 1
    else :
      arr[i][j] = 0
print(arr)

[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]


Создайте массив и отсортируйте его по убыванию.

In [59]:
import numpy as np
from random import randint

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(np.flip(arr))

[10  9  8  7  6  5  4  3  2  1]


Создайте матрицу, выведите ее форму, размер и размерность.

In [60]:
import numpy
from numpy import ndarray

arr = np.arange(27).reshape(3, 3, 3)
print(arr.ndim)
print(arr.size)
print(arr.shape)

3
27
(3, 3, 3)


Найдитн евклидово расстояние между двумя Series (точками) a и b, не
используя встроенную формулу.

In [61]:
import pandas as pd
import math

x = pd.Series(dtype=int)
y = pd.Series(dtype=int)

for i in range(2):
    xCoord = int(input("Введите x: "))
    yCoord = int(input("Введите y: "))
    x.at[i] = xCoord
    y.at[i] = yCoord

# Вычисляем расстояние
xs = (x[0] - x[1]) ** 2
ys = (y[0] - y[1]) ** 2
print(math.sqrt(xs + ys))

Введите x: 1
Введите y: 1
Введите x: 1
Введите y: 1
0.0


Найдите в Интернете ссылку на любой csv файл и сформируйте из него
фрейм данных (например, коллекцию фреймов данных можно найти
здесь: https://github.com/akmand/datasets).

In [62]:
import pandas as pd

url = 'https://raw.githubusercontent.com/akmand/datasets/main/melbourne_house_prices.csv'

df = pd.read_csv(url)

print(df.head())

         Date        Suburb  Rooms Type Method    SellerG  Distance  Postcode  \
0  23/09/2017    Aberfeldie      5    h      S    Rendina       7.5      3040   
1  23/09/2017  Airport West      3    h      S       Brad      10.4      3042   
2  23/09/2017  Airport West      3    h      S  Harcourts      10.4      3042   
3  23/09/2017     Albanvale      3    h      S      Bells      14.0      3021   
4  23/09/2017   Albert Park      3    h     VB     Cayzer       3.0      3206   

   Bedroom2  Bathroom  Car  Landsize  BuildingArea  YearBuilt CouncilArea  \
0         5         4  4.0       730         373.0     2014.0         NaN   
1         3         1  2.0       551          96.0     1950.0         NaN   
2         3         2  2.0       593           NaN        NaN         NaN   
3         3         1  2.0       619           NaN        NaN         NaN   
4         3         2  NaN       137         125.0     1890.0         NaN   

   Lattitude  Longtitude             Regionname  P

Проделайте с получившемся из предыдущего задания фреймом данных
те же действия, что и в примерах 2.2.5-2.2.7.

In [65]:
import pandas as pd

url = 'https://raw.githubusercontent.com/akmand/datasets/main/melbourne_house_prices.csv'

df = pd.read_csv(url)

df.head(2)
df.tail(3)
df.shape
df.describe()
df.iloc[1:4]

df[df['Suburb'] == 'Airport West'].head(7)

Date        Suburb  Rooms Type Method    SellerG  Distance  \
1     23/09/2017  Airport West      3    h      S       Brad      10.4   
2     23/09/2017  Airport West      3    h      S  Harcourts      10.4   
502    9/09/2017  Airport West      3    h      S      Barry      10.4   
503    9/09/2017  Airport West      3    h      S     Nelson      10.4   
920   26/08/2017  Airport West      3    h      S      Barry      10.4   
921   26/08/2017  Airport West      3    h      S     Jellis      10.4   
1372  12/08/2017  Airport West      3    u     VB      Barry      10.4   

      Postcode  Bedroom2  Bathroom  Car  Landsize  BuildingArea  YearBuilt  \
1         3042         3         1  2.0       551          96.0     1950.0   
2         3042         3         2  2.0       593           NaN        NaN   
502       3042         3         1  1.0       767           NaN        NaN   
503       3042         3         2  1.0       697         163.0     2017.0   
920       3042         3         1  1.0       697           NaN        NaN   
921       3042         3         1  3.0       626           NaN        NaN   
1372      3042         3         2  1.0       239           NaN        NaN   

        CouncilArea  Lattitude  Longtitude            Regionname  \
1               NaN  -37.72739   144.88235  Western Metropolitan   
2               NaN  -37.72057   144.87558  Western Metropolitan   
502             NaN  -37.72180   144.88391  Western Metropolitan   
503             NaN  -37.72812   144.88735  Western Metropolitan   
920             NaN  -37.73254   144.88321  Western Metropolitan   
921             NaN  -37.71919   144.87842  Western Metropolitan   
1372  Moonee Valley  -37.73351   144.88749  Western Metropolitan   

      Propertycount    Price  
1              3464   850000  
2              3464   860000  
502            3464  1064000  
503            3464  1000001  
920            3464   975500  
921            3464   880000  
1372           3464   700000

In [66]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler

url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'
df = pd.read_csv(url)

print(df.head())

min_max_scaler = MinMaxScaler()
standard_scaler = StandardScaler()

df['sepal_length_cm'] = min_max_scaler.fit_transform(df[['sepal_length_cm']])
df['sepal_width_cm'] = standard_scaler.fit_transform(df[['sepal_width_cm']])

print(df.head())

   sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0              5.1             3.5              1.4             0.2  setosa
1              4.9             3.0              1.4             0.2  setosa
2              4.7             3.2              1.3             0.2  setosa
3              4.6             3.1              1.5             0.2  setosa
4              5.0             3.6              1.4             0.2  setosa
   sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0         0.222222        1.032057              1.4             0.2  setosa
1         0.166667       -0.124958              1.4             0.2  setosa
2         0.111111        0.337848              1.3             0.2  setosa
3         0.083333        0.106445              1.5             0.2  setosa
4         0.194444        1.263460              1.4             0.2  setosa
